#!/bin/sh
if [ "$1" = "remove" ]; then
	rm -rf /usr/lib/enigma2/python/Plugins/Extensions/StreamingCockpit > /dev/null 2>&1
	echo "StreamingCockpit plugin removed successfully."
else
	find /usr/lib/enigma2/python/Plugins/Extensions/StreamingCockpit -type f -name "*.pyo" -exec rm -f {} \; > /dev/null 2>&1
fi
exit 0
